# Branches that trigger a build on commit
trigger:
- dev
- dev-*

# Branches that trigger builds on PR
pr:
- dev
- dev-*

jobs:

- job: Windows
  pool:
    vmImage: 'windows-latest'
  variables:
    _os: Windows
  strategy:
    maxParallel: 4
    matrix:
      Debug:
        _configuration: Debug
      Release:
        _configuration: Release
  timeoutInMinutes: 12
  steps:
    - script: eng\common\cibuild.cmd -configuration $(_configuration) -prepareMachine /p:TestTimeout=180000
      displayName: Build
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
        ArtifactName: '$(_os) $(_configuration)'
      continueOnError: true
      condition: not(succeeded())

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    _os: Linux
  strategy:
    maxParallel: 4
    matrix:
      Debug:
        _configuration: Debug
      Release:
        _configuration: Release
  timeoutInMinutes: 12
  steps:
    - script: ./eng/common/cibuild.sh --configuration $(_configuration) --prepareMachine /p:TestTimeout=240000
      displayName: Build
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_configuration)'
        ArtifactName: '$(_os) $(_configuration)'
      continueOnError: true
      condition: not(succeeded())

